syntax = "proto2";

package replication;

message Request {
     required bytes op = 1;
     required uint64 clientid = 2;
     required uint64 clientreqid = 3;
}

message UnloggedRequest {
     required bytes op = 1;
     required uint64 clientid = 2;
     required uint64 clientreqid = 3;
}

message RequestIDMessage {
    required uint64 client_id = 1;
    required uint64 client_req_id = 2;
}

message LinearizeableOperation {
    required RequestIDMessage rid = 1;
    required uint64 transaction_id = 2;
    required string op = 3;
    required string key = 4;
    required string value = 5;
    required uint32 idx = 6;
    optional uint64 shardtag = 7;
    optional uint64 intkey = 8;
    repeated uint64 predlist = 9;
}

message SuccessorRequestMessage {
    required uint64 p = 1;
    required uint64 s = 2;
    required uint32 predIdx = 3;
    required int32 shardIdx = 4;
}

message DummyOperation {
    required uint64 req_id = 1;
    required uint32 idx = 2;
}